### ISSUE TITLE
AndroidX Migration

### ISSUE THREAD

**Issue by mertceyhan** [funkyidol/CameraXSample#1]
I'm getting an error when I run the app;

Error; This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled.

**Comment by funkyidol** [comment]
Can you please share which version of Android Studio you are using ?

**Comment by mertceyhan** [comment]
Android Studio 3.6.3

**Comment by funkyidol** [comment]
Im using the project on the same version weird that it wont work for you. I will look into this. But in the mean time please see if this helps
https://stackoverflow.com/questions/60506895/android-studio-3-6-1-error-this-project-uses-androidx-dependencies
